### ISSUE TITLE
Request for Model Checkpoint

### ISSUE THREAD

**Issue by passing2961** [jialuli-luka/SELMA#1]
Hi,

Thank you for sharing the code for your interesting work. Currently, I want to conduct a toy experiment using the model checkpoint you've released. Unfortunately, I was unable to find any model checkpoints in your Dropbox folder; I saw only the prompts and the auto-generated image dataset.

Could you please release the model checkpoint?

Best regards,
Young-Jun

**Comment by jialuli-luka** [comment]
Hi Young-Jun,

Thanks for your interest in our work. 

I've released the merged model weights on huggingface. The name for different models are: [jialuliluka/selma-v1-4](https://huggingface.co/jialuliluka/selma-v1-4), [jialuliluka/selma-v2](https://huggingface.co/jialuliluka/selma-v2), [jialuliluka/selma-xl-res512](https://huggingface.co/jialuliluka/selma-xl-res512), [jialuliluka/selma-xl](https://huggingface.co/jialuliluka/selma-xl). You can run inference with these checkpoints by loading them to the stable diffusion pipeline.

Best,
Jialu

**Comment by YuehengLuo** [comment]
Hi，thanks for your work！But it seems that your released checkpoints are not Lora but whole fine-tuned sd. Am I right？

**Comment by jialuli-luka** [comment]
Hi Yueheng,

We merge the lora weights with the backbone when releasing the huggingface checkpoint. 

Best,
Jialu

**Comment by YuehengLuo** [comment]
Thanks! I understand.
